---

- hosts: webservers
  sudo: yes
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/ansible
    max_clients: 5
  vars_prompt:
  - name: username
    prompt: What's your name?

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"
  - name: Start Apache Services
    service: name=httpd enabled=yes state=started
  - name: Deploy configuration file
    template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
      - Restart Apache
  - name: Create ansible directory
    file: path={{ doc_root }} state=directory
  - name: Copy site files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted

#- hosts: dbservers
#  sudo: yes

#  tasks:
#  - name: Ensure Mysql is installed
#    yum: name=mysql-server state=present
#    when: ansible_os_family == "RedHat"
#  - name: start Mysql
#    service: name=mysqld state=started


- hosts: webservers
  sudo: yes

  tasks:
  - name: stop iptables now!!
    service: name=iptables state=stopped

